"""baseline schema

Revision ID: c4f300ba1c33
Revises: 
Create Date: 2026-05-25 17:15:38.267512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f300ba1c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('car_registration', sa.String(length=40), nullable=False),
    sa.Column('car_model', sa.String(length=120), nullable=False),
    sa.Column('car_type', sa.String(length=120), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('car_description', sa.Text(), nullable=True),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('service_option', sa.Enum('in_shop', 'pickup', 'dropoff', 'pickup_and_dropoff', name='serviceoption'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_car_registration'), 'customers', ['car_registration'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('garage_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_costs_name'), 'garage_costs', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_types_name'), 'work_types', ['name'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('skill', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_full_name'), 'workers', ['full_name'], unique=False)
    op.create_table('customer_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=40), nullable=False),
    sa.Column('make', sa.String(length=120), nullable=False),
    sa.Column('vehicle_type', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_vehicles_customer_id'), 'customer_vehicles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_vehicles_registration'), 'customer_vehicles', ['registration'], unique=False)
    op.create_table('garage_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_items_name'), 'garage_items', ['name'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('inventory_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('default_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplier_invoice_ref', sa.String(length=120), nullable=True),
    sa.Column('supplier_invoice_file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garage_item_id'], ['garage_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_receipts_garage_item_id'), 'inventory_receipts', ['garage_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_receipts_supplier_id'), 'inventory_receipts', ['supplier_id'], unique=False)
    op.create_table('job_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'ready', 'invoiced', 'complete', 'closed', 'cancelled', name='jobcardstatus'), nullable=False),
    sa.Column('intake_mode', sa.Enum('in_shop', 'pickup', 'dropoff', 'pickup_and_dropoff', name='serviceoption'), nullable=False),
    sa.Column('picked_up_by_user_id', sa.Integer(), nullable=True),
    sa.Column('pickup_cost_id', sa.Integer(), nullable=True),
    sa.Column('pickup_cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_mode', sa.Enum('in_shop', 'pickup', 'dropoff', 'pickup_and_dropoff', name='serviceoption'), nullable=False),
    sa.Column('dropoff_cost_id', sa.Integer(), nullable=True),
    sa.Column('dropoff_cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_level', sa.String(length=60), nullable=True),
    sa.Column('mileage', sa.String(length=60), nullable=True),
    sa.Column('present_items', sa.Text(), nullable=True),
    sa.Column('other_present_items', sa.Text(), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('invoice_notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['dropoff_cost_id'], ['garage_costs.id'], ),
    sa.ForeignKeyConstraint(['picked_up_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_cost_id'], ['garage_costs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['customer_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_cards_customer_id'), 'job_cards', ['customer_id'], unique=False)
    op.create_index(op.f('ix_job_cards_job_number'), 'job_cards', ['job_number'], unique=True)
    op.create_index(op.f('ix_job_cards_vehicle_id'), 'job_cards', ['vehicle_id'], unique=False)
    op.create_table('vehicle_ownership_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('previous_customer_id', sa.Integer(), nullable=False),
    sa.Column('new_customer_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['previous_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['customer_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_ownership_history_new_customer_id'), 'vehicle_ownership_history', ['new_customer_id'], unique=False)
    op.create_index(op.f('ix_vehicle_ownership_history_previous_customer_id'), 'vehicle_ownership_history', ['previous_customer_id'], unique=False)
    op.create_index(op.f('ix_vehicle_ownership_history_vehicle_id'), 'vehicle_ownership_history', ['vehicle_id'], unique=False)
    op.create_table('inventory_receipt_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_receipt_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('snapshot_before', sa.JSON(), nullable=False),
    sa.Column('snapshot_after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_receipt_id'], ['inventory_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_receipt_audits_actor_user_id'), 'inventory_receipt_audits', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_inventory_receipt_audits_inventory_receipt_id'), 'inventory_receipt_audits', ['inventory_receipt_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.Enum('intermediate', 'final', name='invoicetype'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Enum('not_paid', 'partially_paid', 'paid', name='paymentstatus'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_sent_email', sa.Boolean(), nullable=False),
    sa.Column('is_sent_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_job_card_id'), 'invoices', ['job_card_id'], unique=False)
    op.create_table('job_card_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('garage_cost_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_type', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garage_cost_id'], ['garage_costs.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_card_costs_job_card_id'), 'job_card_costs', ['job_card_id'], unique=False)
    op.create_table('job_card_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('garage_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garage_item_id'], ['garage_items.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_card_items_job_card_id'), 'job_card_items', ['job_card_id'], unique=False)
    op.create_table('job_card_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_card_id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('labour_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_card_works_job_card_id'), 'job_card_works', ['job_card_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garage_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('inventory_receipt_id', sa.Integer(), nullable=True),
    sa.Column('job_card_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('stock_in', 'stock_out', name='stockmovementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garage_item_id'], ['garage_items.id'], ),
    sa.ForeignKeyConstraint(['inventory_receipt_id'], ['inventory_receipts.id'], ),
    sa.ForeignKeyConstraint(['job_card_id'], ['job_cards.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_garage_item_id'), 'stock_movements', ['garage_item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_job_card_id'), 'stock_movements', ['job_card_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_supplier_id'), 'stock_movements', ['supplier_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_stock_movements_supplier_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_job_card_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_garage_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_job_card_works_job_card_id'), table_name='job_card_works')
    op.drop_table('job_card_works')
    op.drop_index(op.f('ix_job_card_items_job_card_id'), table_name='job_card_items')
    op.drop_table('job_card_items')
    op.drop_index(op.f('ix_job_card_costs_job_card_id'), table_name='job_card_costs')
    op.drop_table('job_card_costs')
    op.drop_index(op.f('ix_invoices_job_card_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_receipt_audits_inventory_receipt_id'), table_name='inventory_receipt_audits')
    op.drop_index(op.f('ix_inventory_receipt_audits_actor_user_id'), table_name='inventory_receipt_audits')
    op.drop_table('inventory_receipt_audits')
    op.drop_index(op.f('ix_vehicle_ownership_history_vehicle_id'), table_name='vehicle_ownership_history')
    op.drop_index(op.f('ix_vehicle_ownership_history_previous_customer_id'), table_name='vehicle_ownership_history')
    op.drop_index(op.f('ix_vehicle_ownership_history_new_customer_id'), table_name='vehicle_ownership_history')
    op.drop_table('vehicle_ownership_history')
    op.drop_index(op.f('ix_job_cards_vehicle_id'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_job_number'), table_name='job_cards')
    op.drop_index(op.f('ix_job_cards_customer_id'), table_name='job_cards')
    op.drop_table('job_cards')
    op.drop_index(op.f('ix_inventory_receipts_supplier_id'), table_name='inventory_receipts')
    op.drop_index(op.f('ix_inventory_receipts_garage_item_id'), table_name='inventory_receipts')
    op.drop_table('inventory_receipts')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_garage_items_name'), table_name='garage_items')
    op.drop_table('garage_items')
    op.drop_index(op.f('ix_customer_vehicles_registration'), table_name='customer_vehicles')
    op.drop_index(op.f('ix_customer_vehicles_customer_id'), table_name='customer_vehicles')
    op.drop_table('customer_vehicles')
    op.drop_index(op.f('ix_workers_full_name'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_work_types_name'), table_name='work_types')
    op.drop_table('work_types')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_garage_costs_name'), table_name='garage_costs')
    op.drop_table('garage_costs')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_car_registration'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
